.DEFAULT_GOAL := help


help:
	@echo 'Available commands:'
	@echo -e 'runserver \t\t - \t Runs Django server'

###################################################################################
# WebServer
###################################################################################

runserver:
	python ./src/manage.py runserver